;
; File generated by cc65 v 2.19 - Git 4232e7a
;
	.fopt		compiler,"cc65 v 2.19 - Git 4232e7a"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_waitvsync
	.import		_kbhit
	.import		_cgetc
	.import		_memcpy
	.import		_memset
	.import		_rand
	.export		_main

.segment	"RODATA"

_spr_bit:
	.byte	$01
	.byte	$02
	.byte	$04
	.byte	$08
	.byte	$10
	.byte	$20
	.byte	$40
	.byte	$80
S01C6:
	.byte	$D3,$C5,$C1,$CC,$20,$37,$35,$25,$20,$D4,$CF,$20,$C3,$CC,$C5,$C1
	.byte	$D2,$20,$C1,$20,$CC,$C5,$D6,$C5,$CC,$00
S01BE:
	.byte	$C1,$20,$CA,$C5,$DA,$DA,$C2,$C1,$CC,$CC,$20,$C3,$CC,$CF,$CE,$C5
	.byte	$20,$C6,$CF,$D2,$20,$C3,$36,$34,$00
S01CC:
	.byte	$D0,$D2,$C5,$D3,$D3,$20,$C6,$C9,$D2,$C5,$20,$D4,$CF,$20,$D2,$C5
	.byte	$D3,$D4,$C1,$D2,$D4,$00
S01C5:
	.byte	$20,$20,$20,$20,$20,$20,$20,$3D,$20,$C2,$D5,$C9,$CC,$C4,$20,$D7
	.byte	$C1,$CC,$CC,$00
S01C7:
	.byte	$D0,$D2,$C5,$D3,$D3,$20,$C6,$C9,$D2,$C5,$20,$D4,$CF,$20,$D3,$D4
	.byte	$C1,$D2,$D4,$00
S01BF:
	.byte	$CA,$CF,$D9,$D3,$D4,$C9,$C3,$CB,$20,$D0,$CF,$D2,$D4,$20,$32,$00
S01BD:
	.byte	$CD,$20,$CF,$20,$CC,$20,$D4,$20,$C2,$20,$C1,$20,$CC,$20,$CC,$00
S01CB:
	.byte	$CC,$C5,$D6,$C5,$CC,$20,$D2,$C5,$C1,$C3,$C8,$C5,$C4,$3A,$20,$00
S01C3:
	.byte	$20,$20,$20,$20,$3D,$20,$D6,$C5,$D2,$D4,$C9,$C3,$C1,$CC,$00
S01C1:
	.byte	$20,$3D,$20,$C8,$CF,$D2,$C9,$DA,$CF,$CE,$D4,$C1,$CC,$00
S01C0:
	.byte	$CC,$C5,$C6,$D4,$2F,$D2,$C9,$C7,$C8,$D4,$00
S01C8:
	.byte	$D4,$C9,$CD,$C5,$20,$D5,$D0,$21,$20,$00
S01C9:
	.byte	$C7,$C1,$CD,$C5,$20,$CF,$D6,$C5,$D2,$00
S01CA:
	.byte	$D3,$C3,$CF,$D2,$C5,$3A,$20,$00
S001B:
	.byte	$C3,$4C,$45,$41,$52,$45,$44,$00
S01C2:
	.byte	$D5,$D0,$2F,$C4,$CF,$D7,$CE,$00
S01BC:
	.byte	$CC,$C5,$D6,$C5,$CC,$20,$00
S0018:
	.byte	$CC,$45,$56,$45,$4C,$00
S001A:
	.byte	$D3,$43,$4F,$52,$45,$00
S0017:
	.byte	$CC,$49,$56,$45,$53,$00
S0019:
	.byte	$D4,$49,$4D,$45,$00
S01C4:
	.byte	$C6,$C9,$D2,$C5,$00
S001C:
	.byte	$25,$00

.segment	"BSS"

_bx:
	.res	14,$00
_by:
	.res	7,$00
_bdx:
	.res	7,$00
_bdy:
	.res	7,$00
_bact:
	.res	7,$00
_banim:
	.res	7,$00
_wcx:
	.res	2,$00
_wcy:
	.res	2,$00
_wdcx:
	.res	2,$00
_wdcy:
	.res	2,$00
_wact:
	.res	2,$00
_wcol:
	.res	2,$00
_wpfv:
	.res	2,$00
_num_balls:
	.res	1,$00
_level:
	.res	1,$00
_lives:
	.res	1,$00
_game_over:
	.res	1,$00
_joy_prev:
	.res	1,$00
_frame_count:
	.res	1,$00
_wall_dir:
	.res	1,$00
_last_cursor_dir:
	.res	1,$00
_joy_hold_frames:
	.res	1,$00
_score:
	.res	2,$00
_cursor_px:
	.res	2,$00
_total_cells:
	.res	2,$00
_filled_cells:
	.res	2,$00
_cursor_py:
	.res	1,$00
_fill_target:
	.res	2,$00
_time_left:
	.res	2,$00
_frames_per_sec:
	.res	1,$00
_time_frames:
	.res	1,$00
_pfmap:
	.res	1000,$00
_pfr:
	.res	50,$00
_scr_row:
	.res	50,$00
_fsx:
	.res	200,$00
_fsy:
	.res	200,$00
_fsp:
	.res	1,$00
_fv_active:
	.res	1,$00
_fv_row:
	.res	1,$00
_spr_x_lo:
	.res	8,$00
_spr_x_hi:
	.res	8,$00
_spr_y:
	.res	8,$00
_cur_px:
	.res	2,$00
_cur_npx:
	.res	2,$00
_cur_py:
	.res	1,$00
_cur_npy:
	.res	1,$00
_cur_i:
	.res	1,$00
_walls_building:
	.res	1,$00
_wall_hit_idx:
	.res	1,$00
_wall_tick:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ scr_put (unsigned char x, unsigned char y, unsigned char ch, unsigned char col)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_scr_put: near

.segment	"CODE"

	jsr     pusha
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0004
	inx
	clc
L0004:	adc     #<(_scr_row)
	tay
	txa
	adc     #>(_scr_row)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0003
	inx
L0003:	jsr     pushax
	clc
	ldy     #$00
	lda     (c_sp),y
	sta     ptr1
	lda     #$4C
	iny
	adc     (c_sp),y
	sta     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	ldy     #$00
	sta     (ptr1),y
	clc
	lda     (c_sp),y
	sta     ptr1
	lda     #$D8
	iny
	adc     (c_sp),y
	sta     ptr1+1
	iny
	lda     (c_sp),y
	ldy     #$00
	sta     (ptr1),y
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ scrwrite (unsigned char x, unsigned char y, const char *s, unsigned char col)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_scrwrite: near

.segment	"CODE"

	jsr     pusha
	ldy     #$03
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L001E
	inx
	clc
L001E:	adc     #<(_scr_row)
	tay
	txa
	adc     #>(_scr_row)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L001C
	inx
L001C:	jsr     pushax
	jmp     L0004
L0002:	ldy     #$04
	jsr     ldptr1ysp
	ldy     #$00
	lda     (ptr1),y
	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	cmp     #$41
	bcc     L0023
	cmp     #$5B
	bcs     L0023
	ldx     #$00
	lda     (c_sp),y
	ldy     #$41
	jsr     decaxy
	clc
	adc     #$01
	ldy     #$00
	jmp     L001D
L0023:	lda     (c_sp),y
	cmp     #$C1
	bcc     L0028
	cmp     #$DB
	bcs     L0028
	ldx     #$00
	lda     (c_sp),y
	ldy     #$C1
	jsr     decaxy
	clc
	adc     #$01
	ldy     #$00
	jmp     L001D
L0028:	lda     (c_sp),y
	cmp     #$30
	bcc     L002D
	cmp     #$3A
	bcs     L002D
	ldx     #$00
	lda     (c_sp),y
	ldy     #$30
	jsr     decaxy
	jsr     incaxy
	ldy     #$00
	jmp     L001D
L002D:	lda     (c_sp),y
	cmp     #$20
	beq     L001D
	cmp     #$3A
	beq     L001D
	cmp     #$25
	beq     L001D
	cmp     #$21
	bne     L001A
L001D:	sta     (c_sp),y
L001A:	clc
	iny
	lda     (c_sp),y
	sta     ptr1
	lda     #$4C
	iny
	adc     (c_sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (c_sp),y
	sta     (ptr1),y
	clc
	iny
	lda     (c_sp),y
	sta     ptr1
	lda     #$D8
	iny
	adc     (c_sp),y
	sta     ptr1+1
	iny
	lda     (c_sp),y
	ldy     #$00
	sta     (ptr1),y
	iny
	ldx     #$00
	tya
	jsr     addeqysp
	ldy     #$04
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jsr     incsp1
L0004:	ldy     #$04
	jsr     ldptr1ysp
	ldy     #$00
	lda     (ptr1),y
	jne     L0002
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ scr_num (unsigned char x, unsigned char y, unsigned int val, unsigned char col)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_scr_num: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp6
	lda     #$05
	jsr     pusha
	lda     #$00
	ldy     #$06
	sta     (c_sp),y
	ldy     #$08
	lda     (c_sp),y
	iny
	ora     (c_sp),y
	bne     L000E
	lda     #$30
	ldy     #$05
	sta     (c_sp),y
	lda     #$04
	ldy     #$00
	sta     (c_sp),y
	jmp     L0006
L000D:	lda     (c_sp),y
	sec
	sbc     #$01
	sta     (c_sp),y
	jsr     incax1
	jsr     leaaxsp
	jsr     pushax
	ldy     #$0D
	jsr     pushwysp
	lda     #$0A
	jsr     tosumoda0
	ldy     #$30
	jsr     incaxy
	ldy     #$00
	jsr     staspidx
	ldy     #$0B
	jsr     pushwysp
	lda     #$0A
	jsr     tosudiva0
	ldy     #$08
	jsr     staxysp
	ldy     #$09
L000E:	lda     (c_sp),y
	dey
	ora     (c_sp),y
	beq     L0006
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	bne     L000D
L0006:	ldy     #$0B
	lda     (c_sp),y
	jsr     pusha
	ldy     #$0B
	lda     (c_sp),y
	jsr     pusha
	lda     #$03
	jsr     leaa0sp
	ldy     #$02
	clc
	adc     (c_sp),y
	bcc     L000B
	inx
L000B:	jsr     pushax
	ldy     #$0B
	lda     (c_sp),y
	jsr     _scrwrite
	ldy     #$0C
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ scr_num_pad (unsigned char x, unsigned char y, unsigned int val, unsigned char width, unsigned char col)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_scr_num_pad: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp7
	lda     #$00
	tay
L0010:	sta     (c_sp),y
	cmp     #$05
	bcs     L0011
	lda     #$01
	jsr     leaa0sp
	sta     ptr1
	stx     ptr1+1
	lda     (c_sp),y
	tay
	lda     #$30
	sta     (ptr1),y
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0010
L0011:	tya
	ldy     #$06
	sta     (c_sp),y
	lda     #$05
	ldy     #$00
	sta     (c_sp),y
	ldy     #$09
	lda     (c_sp),y
	iny
	ora     (c_sp),y
	bne     L0014
	lda     #$30
	ldy     #$05
	sta     (c_sp),y
	jmp     L000B
L0013:	lda     (c_sp),y
	sec
	sbc     #$01
	sta     (c_sp),y
	jsr     incax1
	jsr     leaaxsp
	jsr     pushax
	ldy     #$0E
	jsr     pushwysp
	lda     #$0A
	jsr     tosumoda0
	ldy     #$30
	jsr     incaxy
	ldy     #$00
	jsr     staspidx
	ldy     #$0C
	jsr     pushwysp
	lda     #$0A
	jsr     tosudiva0
	ldy     #$09
	jsr     staxysp
	ldy     #$0A
L0014:	lda     (c_sp),y
	dey
	ora     (c_sp),y
	beq     L000B
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	bne     L0013
L000B:	ldy     #$0C
	lda     (c_sp),y
	jsr     pusha
	ldy     #$0C
	lda     (c_sp),y
	jsr     pusha
	lda     #$08
	jsr     leaa0sp
	sec
	ldy     #$0A
	sbc     (c_sp),y
	pha
	txa
	sbc     #$00
	tax
	pla
	jsr     pushax
	ldy     #$0B
	lda     (c_sp),y
	jsr     _scrwrite
	ldy     #$0D
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ clear_screen (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clear_screen: near

.segment	"CODE"

	jsr     decsp2
	ldx     #$00
	txa
	jsr     stax0sp
L0002:	ldy     #$01
	lda     (c_sp),y
	cmp     #$03
	bne     L0006
	dey
	lda     (c_sp),y
	cmp     #$E8
L0006:	bcs     L0003
	clc
	ldy     #$00
	lda     (c_sp),y
	sta     ptr1
	lda     #$4C
	iny
	adc     (c_sp),y
	sta     ptr1+1
	lda     #$20
	dey
	sta     (ptr1),y
	clc
	lda     (c_sp),y
	sta     ptr1
	lda     #$D8
	iny
	adc     (c_sp),y
	sta     ptr1+1
	lda     #$00
	dey
	sta     (ptr1),y
	tax
	lda     #$01
	jsr     addeq0sp
	jmp     L0002
L0003:	lda     #<(_pfmap)
	ldx     #>(_pfmap)
	jsr     pushax
	lda     #$01
	jsr     pusha0
	ldx     #$03
	lda     #$E8
	jsr     _memset
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ init_tables (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_tables: near

.segment	"CODE"

	jsr     decsp1
	jsr     push0
	ldy     #$02
L0008:	sta     (c_sp),y
	cmp     #$19
	bcs     L0003
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0009
	inx
	clc
L0009:	adc     #<(_scr_row)
	sta     ptr1
	txa
	adc     #>(_scr_row)
	sta     ptr1+1
	jsr     ldax0sp
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	iny
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L000A
	inx
	clc
L000A:	adc     #<(_pfr)
	sta     ptr1
	txa
	adc     #>(_pfr)
	sta     ptr1+1
	jsr     ldax0sp
	clc
	adc     #<(_pfmap)
	tay
	txa
	adc     #>(_pfmap)
	tax
	tya
	ldy     #$00
	sta     (ptr1),y
	iny
	txa
	sta     (ptr1),y
	ldx     #$00
	lda     #$28
	jsr     addeq0sp
	ldy     #$02
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0008
L0003:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ detect_system (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_detect_system: near

.segment	"CODE"

	jsr     decsp2
L000E:	lda     $D012
	bne     L000E
L000F:	lda     $D012
	cmp     #$02
	bcc     L000F
	jmp     L0012
L0011:	lda     $D011
	ldx     #$00
	and     #$80
	asl     a
	bcc     L000C
	inx
L000C:	ora     $D012
	jsr     stax0sp
	cmp     #$23
	txa
	sbc     #$01
	bcc     L0012
	lda     #$32
	jmp     L000D
L0012:	lda     $D012
	cmp     #$02
	bcs     L0011
	lda     #$3C
L000D:	sta     _frames_per_sec
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ setup_vic (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_setup_vic: near

.segment	"CODE"

	jsr     decsp2
	jsr     _detect_system
	jsr     _init_tables
	sei
	lda     $0001
	and     #$FB
	sta     $0001
	ldx     #$40
	lda     #$00
	jsr     pushax
	ldx     #$D0
	jsr     pushax
	ldx     #$08
	jsr     _memcpy
	lda     $0001
	ora     #$04
	sta     $0001
	cli
	ldx     #$44
	lda     #$00
	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$FE
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax1
	sta     ptr1
	stx     ptr1+1
	lda     #$FE
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	lda     #$FE
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax3
	sta     ptr1
	stx     ptr1+1
	lda     #$FE
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax4
	sta     ptr1
	stx     ptr1+1
	lda     #$FE
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax5
	sta     ptr1
	stx     ptr1+1
	lda     #$FE
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax6
	sta     ptr1
	stx     ptr1+1
	lda     #$FE
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax7
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	ldx     #$44
	lda     #$08
	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax1
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax3
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax4
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax5
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax6
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax7
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	ldx     #$44
	lda     #$10
	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax1
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax3
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax4
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax5
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax6
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax7
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	ldx     #$44
	lda     #$18
	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax1
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax3
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax4
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax5
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax6
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax7
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	ldx     #$44
	lda     #$20
	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax1
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax3
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax4
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax5
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax6
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax7
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	ldx     #$44
	lda     #$28
	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax1
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax3
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax4
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax5
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax6
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax7
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	ldx     #$44
	lda     #$30
	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax1
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax3
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax4
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax5
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax6
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax7
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	ldx     #$44
	lda     #$38
	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax1
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax3
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax4
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax5
	sta     ptr1
	stx     ptr1+1
	lda     #$C0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax6
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax7
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	ldx     #$44
	lda     #$40
	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax1
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax2
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax3
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax4
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax5
	sta     ptr1
	stx     ptr1+1
	lda     #$03
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax6
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	jsr     incax7
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	lda     $DD00
	and     #$FC
	ora     #$02
	sta     $DD00
	lda     #$30
	sta     $D018
	tya
	sta     $D021
	sta     $D020
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ restore_vic (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_restore_vic: near

.segment	"CODE"

	lda     $DD00
	and     #$FC
	ora     #$03
	sta     $DD00
	lda     #$15
	sta     $D018
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ gen_ball (unsigned int addr, unsigned char wl, unsigned char wr)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_gen_ball: near

.segment	"CODE"

	jsr     pusha
	ldy     #$05
	jsr     pushwysp
	jsr     decsp7
	ldy     #$08
	jsr     ldptr1ysp
	lda     #$00
	ldy     #$3E
L001A:	sta     (ptr1),y
	dey
	bpl     L001A
	lda     #$04
	ldy     #$06
L001E:	sta     (c_sp),y
	cmp     #$10
	jcs     L0003
	lda     (c_sp),y
	cmp     #$04
	beq     L0021
	cmp     #$0F
	bne     L0023
L0021:	lda     #$05
	ldy     #$04
	sta     (c_sp),y
	lda     #$06
	jmp     L002B
L0023:	lda     (c_sp),y
	cmp     #$05
	beq     L0024
	cmp     #$0E
	bne     L0025
L0024:	lda     #$04
	tay
	sta     (c_sp),y
	lda     #$07
	jmp     L002B
L0025:	lda     #$03
	ldy     #$04
	sta     (c_sp),y
	lda     #$08
L002B:	dey
	sta     (c_sp),y
	iny
	lda     (c_sp),y
	iny
L001D:	sta     (c_sp),y
	ldy     #$03
	cmp     (c_sp),y
	beq     L0026
	jcs     L0004
L0026:	lda     #$02
	dey
	sta     (c_sp),y
	ldy     #$05
	lda     (c_sp),y
	ldy     #$0A
	cmp     (c_sp),y
	bcc     L0012
	ldy     #$05
	lda     (c_sp),y
	ldy     #$09
	cmp     (c_sp),y
	bcc     L0028
	bne     L0012
L0028:	lda     #$03
	ldy     #$02
	sta     (c_sp),y
L0012:	ldy     #$06
	lda     (c_sp),y
	cmp     #$07
	bne     L0016
	dey
	lda     (c_sp),y
	cmp     #$06
	bne     L002C
	lda     #$03
	ldy     #$02
	sta     (c_sp),y
L0016:	ldy     #$05
L002C:	lda     (c_sp),y
	lsr     a
	lsr     a
	ldy     #$01
	sta     (c_sp),y
	lda     #$03
	jsr     pusha0
	ldy     #$07
	lda     (c_sp),y
	and     #$03
	jsr     tossuba0
	asl     a
	ldy     #$00
	sta     (c_sp),y
	ldx     #$00
	ldy     #$06
	lda     (c_sp),y
	jsr     mulax3
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L001F
	inx
	clc
L001F:	ldy     #$07
	adc     (c_sp),y
	pha
	txa
	iny
	adc     (c_sp),y
	tax
	pla
	sta     ptr2
	stx     ptr2+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     sreg
	ldx     #$00
	ldy     #$02
	lda     (c_sp),y
	sta     ptr1
	lda     (c_sp,x)
	tay
	lda     ptr1
	jsr     aslaxy
	ora     sreg
	ldy     #$00
	sta     (ptr2),y
	ldy     #$05
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L001D
L0004:	ldy     #$06
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L001E
L0003:	ldy     #$0D
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ make_cursor (unsigned int addr, unsigned char vert)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_make_cursor: near

.segment	"CODE"

	jsr     pusha
	ldy     #$04
	jsr     pushwysp
	jsr     ldptr10sp
	lda     #$00
	ldy     #$3E
L0004:	sta     (ptr1),y
	dey
	bpl     L0004
	ldy     #$02
	lda     (c_sp),y
	jne     L0002
	jsr     ldax0sp
	ldy     #$15
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$02
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$16
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$17
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$40
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$18
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$06
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$19
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$1A
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$60
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$1B
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$0F
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$1C
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$1D
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$F0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$1E
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$1F
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$1F
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$20
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$F8
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$21
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$0F
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$22
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$23
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$F0
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$24
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$06
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$25
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$26
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$60
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$27
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$02
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$28
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$29
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$40
	jmp     L0006
L0002:	jsr     ldax0sp
	ldy     #$0C
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$0D
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$18
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$0E
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$0F
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$10
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$3C
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$11
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$12
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$13
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$7E
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$14
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$15
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$16
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$17
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$18
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$19
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$18
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$1A
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$1B
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$1C
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$18
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$1D
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$1E
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$1F
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$18
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$20
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$21
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$22
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$18
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$23
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$24
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$25
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$18
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$26
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$27
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$28
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$FF
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$29
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$2A
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$2B
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$7E
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$2C
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$2D
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$2E
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$3C
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$2F
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$30
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$31
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$18
	ldy     #$00
	sta     (ptr1),y
	jsr     ldax0sp
	ldy     #$32
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     #$00
L0006:	ldy     #$00
	sta     (ptr1),y
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ init_sprites (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_sprites: near

.segment	"CODE"

	jsr     decsp1
	ldx     #$48
	lda     #$00
	jsr     pushax
	jsr     _make_cursor
	ldx     #$48
	lda     #$40
	jsr     pushax
	lda     #$01
	jsr     _make_cursor
	ldx     #$48
	lda     #$80
	jsr     pushax
	lda     #$63
	jsr     pusha
	lda     #$00
	jsr     _gen_ball
	ldx     #$48
	lda     #$C0
	jsr     pushax
	lda     #$03
	jsr     pusha
	lda     #$05
	jsr     _gen_ball
	ldx     #$49
	lda     #$00
	jsr     pushax
	lda     #$03
	jsr     pusha
	lda     #$07
	jsr     _gen_ball
	ldx     #$49
	lda     #$40
	jsr     pushax
	lda     #$03
	jsr     pusha
	lda     #$08
	jsr     _gen_ball
	ldx     #$49
	lda     #$80
	jsr     pushax
	lda     #$06
	jsr     pusha
	lda     #$08
	jsr     _gen_ball
	ldx     #$49
	lda     #$C0
	jsr     pushax
	lda     #$08
	jsr     pusha
	jsr     _gen_ball
	lda     #$20
	sta     $4FF8
	lda     #$01
	ldy     #$00
L000C:	sta     (c_sp),y
	cmp     #$08
	bcs     L000E
	lda     (c_sp),y
	tay
	lda     #$22
	sta     $4FF8,y
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L000C
L000E:	lda     #$01
	sta     $D027
L000D:	sta     (c_sp),y
	cmp     #$08
	bcs     L000F
	lda     (c_sp),y
	tay
	lda     #$02
	sta     $D027,y
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L000D
L000F:	lda     #$FE
	sta     $D01C
	lda     #$09
	sta     $D025
	lda     #$01
	sta     $D026
	tya
	sta     $D01D
	sta     $D017
	sta     $D01B
	lda     #$01
	sta     $D015
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ set_spr (unsigned char spr, unsigned int x, unsigned char y)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_set_spr: near

.segment	"CODE"

	jsr     pusha
	ldy     #$03
	lda     (c_sp),y
	tax
	ldy     #$01
	lda     (c_sp),y
	sta     _spr_x_lo,x
	lda     #<(_spr_x_hi)
	ldx     #>(_spr_x_hi)
	ldy     #$03
	clc
	adc     (c_sp),y
	bcc     L0003
	inx
L0003:	sta     ptr1
	stx     ptr1+1
	dey
	lda     (c_sp),y
	and     #$01
	ldy     #$00
	sta     (ptr1),y
	ldy     #$03
	lda     (c_sp),y
	tax
	ldy     #$00
	lda     (c_sp),y
	sta     _spr_y,x
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ flush_sprites (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_flush_sprites: near

.segment	"CODE"

	ldy     #$00
	ldx     #$00
SP_loop:
	lda     _spr_x_lo,x
	sta     $D000,y
	lda     _spr_y,x
	sta     $D001,y
	inx
	iny
	iny
	cpx     #$08
	bne     SP_loop
	lda     #$00
	dex
SP_msb:	asl     a
	ora     _spr_x_hi,x
	dex
	bpl     SP_msb
	sta     $D010
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ draw_border (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_border: near

.segment	"CODE"

	jsr     decsp1
	lda     #$02
	ldy     #$00
L0012:	sta     (c_sp),y
	cmp     #$26
	bcs     L0016
	lda     (c_sp),y
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     #$81
	jsr     pusha
	lda     #$0C
	jsr     _scr_put
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0012
L0016:	lda     #$02
L0013:	sta     (c_sp),y
	cmp     #$26
	bcs     L0017
	lda     (c_sp),y
	jsr     pusha
	lda     #$16
	jsr     pusha
	lda     #$82
	jsr     pusha
	lda     #$0C
	jsr     _scr_put
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0013
L0017:	lda     #$03
L0014:	sta     (c_sp),y
	cmp     #$16
	bcs     L0018
	lda     #$01
	jsr     pusha
	tay
	lda     (c_sp),y
	jsr     pusha
	lda     #$83
	jsr     pusha
	lda     #$0C
	jsr     _scr_put
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0014
L0018:	lda     #$03
L0015:	sta     (c_sp),y
	cmp     #$16
	bcs     L0019
	lda     #$26
	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	jsr     pusha
	lda     #$84
	jsr     pusha
	lda     #$0C
	jsr     _scr_put
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0015
L0019:	lda     #$01
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     #$85
	jsr     pusha
	lda     #$0C
	jsr     _scr_put
	lda     #$26
	jsr     pusha
	lda     #$02
	jsr     pusha
	lda     #$86
	jsr     pusha
	lda     #$0C
	jsr     _scr_put
	lda     #$01
	jsr     pusha
	lda     #$16
	jsr     pusha
	lda     #$87
	jsr     pusha
	lda     #$0C
	jsr     _scr_put
	lda     #$26
	jsr     pusha
	lda     #$16
	jsr     pusha
	lda     #$88
	jsr     pusha
	lda     #$0C
	jsr     _scr_put
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ clear_field (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_clear_field: near

.segment	"CODE"

	jsr     decsp2
	lda     #$03
	ldy     #$00
L000D:	sta     (c_sp),y
	cmp     #$16
	bcs     L0003
	lda     #$02
	iny
L000C:	sta     (c_sp),y
	cmp     #$26
	bcs     L0004
	lda     (c_sp),y
	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	jsr     pusha
	lda     #$80
	jsr     pusha
	lda     #$0F
	jsr     _scr_put
	ldx     #$00
	lda     (c_sp,x)
	asl     a
	bcc     L000E
	inx
	clc
L000E:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L000B
	inx
L000B:	sta     ptr1
	stx     ptr1+1
	lda     #$00
	dey
	sta     (ptr1),y
	iny
	clc
	tya
	adc     (c_sp),y
	jmp     L000C
L0004:	dey
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L000D
L0003:	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ draw_hud_labels (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_hud_labels: near

.segment	"CODE"

	lda     #$01
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #<(S0017)
	ldx     #>(S0017)
	jsr     pushax
	lda     #$01
	jsr     _scrwrite
	lda     #$10
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #<(S0018)
	ldx     #>(S0018)
	jsr     pushax
	lda     #$01
	jsr     _scrwrite
	lda     #$1F
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     #<(S0019)
	ldx     #>(S0019)
	jsr     pushax
	lda     #$01
	jsr     _scrwrite
	lda     #$01
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     #<(S001A)
	ldx     #>(S001A)
	jsr     pushax
	lda     #$01
	jsr     _scrwrite
	lda     #$1C
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     #<(S001B)
	ldx     #>(S001B)
	jsr     pushax
	lda     #$01
	jmp     _scrwrite

.endproc

; ---------------------------------------------------------------
; void __near__ draw_hud (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_draw_hud: near

.segment	"CODE"

	lda     _total_cells
	ldx     _total_cells+1
	jsr     shrax2
	jsr     pushax
	lda     #$00
	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	iny
	ora     (c_sp),y
	beq     L0002
	lda     _filled_cells
	ldx     _filled_cells+1
	jsr     pushax
	lda     #$19
	jsr     tosumula0
	jsr     pushax
	ldy     #$04
	jsr     ldaxysp
	jsr     tosudivax
	ldy     #$00
	sta     (c_sp),y
L0002:	ldy     #$00
	lda     (c_sp),y
	cmp     #$65
	bcc     L0008
	lda     #$64
	sta     (c_sp),y
L0008:	lda     #$07
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     _lives
	jsr     pusha0
	lda     #$02
	jsr     pusha
	lda     #$01
	jsr     _scr_num_pad
	lda     #$16
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     _level
	jsr     pusha0
	lda     #$02
	jsr     pusha
	lda     #$01
	jsr     _scr_num_pad
	lda     #$24
	jsr     pusha
	lda     #$00
	jsr     pusha
	lda     _time_left
	ldx     _time_left+1
	jsr     pushax
	lda     #$03
	jsr     pusha
	lda     _time_left+1
	cmp     #$00
	bne     L0005
	lda     _time_left
	cmp     #$0B
L0005:	bcs     L0009
	lda     #$02
	jmp     L000A
L0009:	lda     #$01
L000A:	jsr     _scr_num_pad
	lda     #$07
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     _score
	ldx     _score+1
	jsr     pushax
	lda     #$05
	jsr     pusha
	lda     #$01
	jsr     _scr_num_pad
	lda     #$24
	jsr     pusha
	lda     #$18
	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha0
	lda     #$02
	jsr     pusha
	lda     #$01
	jsr     _scr_num_pad
	lda     #$26
	jsr     pusha
	lda     #$18
	jsr     pusha
	lda     #<(S001C)
	ldx     #>(S001C)
	jsr     pushax
	lda     #$01
	jsr     _scrwrite
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ init_balls (unsigned char count)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_balls: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp2
	ldy     #$02
	lda     (c_sp),y
	sta     _num_balls
	lda     (c_sp),y
	cmp     #$08
	lda     #$00
	bcc     L001C
	lda     #$07
	sta     (c_sp),y
	lda     #$00
L001C:	dey
L0018:	sta     (c_sp),y
	iny
	cmp     (c_sp),y
	jcs     L001F
	dey
	lda     (c_sp),y
	tay
	lda     #$01
	sta     _bact,y
	tay
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L001A
	inx
	clc
L001A:	adc     #<(_bx)
	tay
	txa
	adc     #>(_bx)
	tax
	tya
	jsr     pushax
	jsr     _rand
	jsr     pushax
	ldx     #$00
	lda     #$F8
	jsr     tosmoda0
	ldy     #$24
	jsr     incaxy
	ldy     #$00
	jsr     staxspidx
	lda     #<(_by)
	ldx     #>(_by)
	iny
	clc
	adc     (c_sp),y
	bcc     L0008
	inx
L0008:	jsr     pushax
	jsr     _rand
	jsr     pushax
	ldx     #$00
	lda     #$70
	jsr     tosmoda0
	ldy     #$2C
	jsr     incaxy
	ldy     #$00
	jsr     staspidx
	lda     #<(_bdx)
	ldx     #>(_bdx)
	ldy     #$01
	clc
	adc     (c_sp),y
	bcc     L0009
	inx
L0009:	jsr     pushax
	jsr     _rand
	and     #$01
	beq     L000A
	lda     #$01
	jmp     L001D
L000A:	lda     #$FF
L001D:	cmp     #$80
	ldy     #$00
	jsr     staspidx
	lda     #<(_bdy)
	ldx     #>(_bdy)
	ldy     #$01
	clc
	adc     (c_sp),y
	bcc     L000D
	inx
L000D:	jsr     pushax
	jsr     _rand
	and     #$01
	beq     L000E
	lda     #$01
	jmp     L001E
L000E:	lda     #$FF
L001E:	cmp     #$80
	ldy     #$00
	jsr     staspidx
	lda     #<(_banim)
	ldx     #>(_banim)
	ldy     #$01
	clc
	adc     (c_sp),y
	bcc     L0011
	inx
L0011:	jsr     pushax
	jsr     _rand
	jsr     pushax
	ldx     #$00
	lda     #$06
	jsr     tosmoda0
	ldy     #$00
	jsr     staspidx
	ldy     #$01
	lda     (c_sp),y
	tay
	lda     #$02
	sta     $D028,y
	ldy     #$01
	clc
	tya
	adc     (c_sp),y
	jmp     L0018
L001F:	lda     #$01
	ldy     #$00
	sta     (c_sp),y
	tya
	iny
L0019:	sta     (c_sp),y
	iny
	cmp     (c_sp),y
	bcs     L0014
	ldx     #$00
	lda     (c_sp,x)
	jsr     pusha0
	ldy     #$03
	lda     (c_sp),y
	jsr     incax1
	sta     ptr1
	txa
	clc
	adc     #>(_spr_bit)
	sta     ptr1+1
	ldy     #<(_spr_bit)
	lda     (ptr1),y
	jsr     tosora0
	ldy     #$00
	sta     (c_sp),y
	iny
	clc
	tya
	adc     (c_sp),y
	jmp     L0019
L0014:	ldy     #$00
	lda     (c_sp),y
	sta     $D015
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ erase_wall (unsigned char idx)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_erase_wall: near

.segment	"CODE"

	jsr     pusha
	lda     #<(_wdcx)
	ldx     #>(_wdcx)
	ldy     #$00
	clc
	adc     (c_sp),y
	bcc     L0018
	inx
L0018:	jsr     ldaidx
	jsr     negax
	jsr     pusha
	lda     #<(_wdcy)
	ldx     #>(_wdcy)
	ldy     #$01
	clc
	adc     (c_sp),y
	bcc     L0004
	inx
L0004:	dey
	jsr     ldaidx
	jsr     negax
	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	tay
	lda     _wcx,y
	jsr     pusha
	ldy     #$03
	lda     (c_sp),y
	tay
	lda     _wcy,y
	jsr     pusha
	ldy     #$04
	lda     (c_sp),y
	tay
	lda     _wpfv,y
	jsr     pusha
	jmp     L000B
L001A:	lda     (c_sp),y
	asl     a
	bcc     L0016
	ldx     #$01
	clc
L0016:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	ldy     #$00
	cmp     (c_sp),y
	bne     L000A
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	jsr     pusha
	lda     #$80
	jsr     pusha
	lda     #$0F
	jsr     _scr_put
	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0017
	inx
	clc
L0017:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0015
	inx
L0015:	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	ldy     #$04
	lda     (c_sp),y
	ldy     #$02
	clc
	adc     (c_sp),y
	sta     (c_sp),y
	iny
	lda     (c_sp),y
	ldy     #$01
	clc
	adc     (c_sp),y
	sta     (c_sp),y
L000B:	ldy     #$02
	lda     (c_sp),y
	cmp     #$02
	bcc     L000A
	cmp     #$26
	bcs     L000A
	dey
	lda     (c_sp),y
	cmp     #$03
	bcc     L000A
	ldx     #$00
	lda     (c_sp),y
	cmp     #$16
	jcc     L001A
L000A:	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ move_one (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_move_one: near

.segment	"CODE"

	ldx     _cur_i
	lda     _bdx,x
	bmi     MO_dx_neg
	clc
	lda     _cur_px
	adc     #1
	sta     _cur_npx
	lda     _cur_px+1
	adc     #0
	sta     _cur_npx+1
	jmp     MO_npx_done
MO_dx_neg:
	sec
	lda     _cur_px
	sbc     #1
	sta     _cur_npx
	lda     _cur_px+1
	sbc     #0
	sta     _cur_npx+1
	ldx     _cur_i
	lda     _cur_py
	clc
	adc     _bdy,x
	sta     _cur_npy
	clc
	lda     _cur_npx
	adc     #6
	sta     $02
	lda     _cur_npx+1
	adc     #0
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	sta     $04
	lda     $02
	lsr     a
	lsr     a
	lsr     a
	ora     $04
	sta     $02
	clc
	lda     _cur_npx
	adc     #17
	sta     $05
	lda     _cur_npx+1
	adc     #0
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	sta     $04
	lda     $05
	lsr     a
	lsr     a
	lsr     a
	ora     $04
	sta     $03
	lda     _walls_building
	jeq     MO_no_wall_chk
	lda     _cur_npy
	clc
	adc     #4
	lsr     a
	lsr     a
	lsr     a
	sta     $04
	lda     _cur_npy
	clc
	adc     #15
	lsr     a
	lsr     a
	lsr     a
	sta     $05
	lda     $04
	asl     a
	tax
	lda     _pfr,x
	sta     $06
	lda     _pfr+1,x
	sta     $07
	ldy     $02
	lda     ($06),y
	cmp     #2
	bcs     L0007
	ldy     $03
	lda     ($06),y
	cmp     #2
	bcs     L0007
	lda     $05
	asl     a
	tax
	lda     _pfr,x
	sta     $06
	lda     _pfr+1,x
	sta     $07
	ldy     $02
	lda     ($06),y
	cmp     #2
	bcs     L0007
	ldy     $03
	lda     ($06),y
	cmp     #2
	jcc     MO_no_wall_chk
L0007:	sbc     #2
	sta     _wall_hit_idx
	lda     _cur_npx
	sta     _cur_px
	lda     _cur_npx+1
	sta     _cur_px+1
	lda     _cur_npy
	sta     _cur_py
	jmp     MO_done

.endproc

; ---------------------------------------------------------------
; void __near__ update_balls (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_balls: near

.segment	"CODE"

	lda     _frame_count
	and     #$07
	jsr     booleq
	jsr     pusha
	stx     _cur_i
L0014:	lda     _cur_i
	cmp     _num_balls
	jcs     L0004
	ldy     _cur_i
	lda     _bact,y
	jeq     L0016
	ldx     #$00
	lda     _cur_i
	asl     a
	bcc     L0012
	inx
	clc
L0012:	adc     #<(_bx)
	tay
	txa
	adc     #>(_bx)
	tax
	tya
	jsr     ldaxi
	sta     _cur_px
	stx     _cur_px+1
	ldy     _cur_i
	lda     _by,y
	sta     _cur_py
	jsr     _move_one
	ldx     #$00
	lda     _cur_i
	asl     a
	bcc     L0013
	inx
	clc
L0013:	adc     #<(_bx)
	sta     ptr1
	txa
	adc     #>(_bx)
	sta     ptr1+1
	lda     _cur_px
	ldy     #$00
	sta     (ptr1),y
	iny
	lda     _cur_px+1
	sta     (ptr1),y
	ldy     _cur_i
	lda     _cur_py
	sta     _by,y
	ldy     #$00
	lda     (c_sp),y
	beq     L0015
	ldy     _cur_i
	lda     _banim,y
	clc
	adc     #$01
	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	cmp     #$06
	bcc     L000D
	tya
	sta     (c_sp),y
L000D:	lda     (c_sp),y
	ldy     _cur_i
	sta     _banim,y
	ldx     #$4F
	lda     #$F9
	clc
	adc     _cur_i
	bcc     L000F
	inx
L000F:	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (c_sp,x)
	ldy     #$22
	jsr     incaxy
	ldy     #$00
	sta     (ptr1),y
	jsr     incsp1
L0015:	lda     _cur_i
	clc
	adc     #$01
	jsr     pusha
	lda     _cur_px
	ldx     _cur_px+1
	ldy     #$18
	jsr     incaxy
	jsr     pushax
	ldx     #$00
	lda     _cur_py
	ldy     #$32
	jsr     incaxy
	jsr     _set_spr
L0016:	inc     _cur_i
	jmp     L0014
L0004:	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ solidify_wall (unsigned char idx)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_solidify_wall: near

.segment	"CODE"

	jsr     pusha
	lda     #<(_wdcx)
	ldx     #>(_wdcx)
	ldy     #$00
	clc
	adc     (c_sp),y
	bcc     L001B
	inx
L001B:	jsr     ldaidx
	jsr     negax
	jsr     pusha
	lda     #<(_wdcy)
	ldx     #>(_wdcy)
	ldy     #$01
	clc
	adc     (c_sp),y
	bcc     L0004
	inx
L0004:	dey
	jsr     ldaidx
	jsr     negax
	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	tay
	lda     _wcx,y
	jsr     pusha
	ldy     #$03
	lda     (c_sp),y
	tay
	lda     _wcy,y
	jsr     pusha
	ldy     #$04
	lda     (c_sp),y
	tay
	lda     _wpfv,y
	jsr     pusha
	jmp     L000B
L001D:	lda     (c_sp),y
	asl     a
	bcc     L0018
	ldx     #$01
	clc
L0018:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	ldy     #$00
	cmp     (c_sp),y
	jne     L000A
	iny
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0019
	inx
	clc
L0019:	adc     #<(_scr_row)
	tay
	txa
	adc     #>(_scr_row)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	clc
	lda     #$D8
	adc     ptr1+1
	sta     ptr1+1
	ldy     #$02
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0016
	inx
L0016:	sta     ptr1
	stx     ptr1+1
	lda     #$00
	tay
	sta     (ptr1),y
	iny
	tax
	lda     (c_sp),y
	asl     a
	bcc     L001A
	inx
	clc
L001A:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0017
	inx
L0017:	sta     ptr1
	stx     ptr1+1
	lda     #$01
	ldy     #$00
	sta     (ptr1),y
	ldy     #$04
	lda     (c_sp),y
	ldy     #$02
	clc
	adc     (c_sp),y
	sta     (c_sp),y
	iny
	lda     (c_sp),y
	ldy     #$01
	clc
	adc     (c_sp),y
	sta     (c_sp),y
L000B:	ldy     #$02
	lda     (c_sp),y
	cmp     #$02
	bcc     L000A
	cmp     #$26
	bcs     L000A
	dey
	lda     (c_sp),y
	cmp     #$03
	bcc     L000A
	ldx     #$00
	lda     (c_sp),y
	cmp     #$16
	jcc     L001D
L000A:	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ fill_regions (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fill_regions: near

.segment	"CODE"

	jsr     decsp5
	lda     #$00
	ldy     #$04
L006A:	sta     (c_sp),y
	cmp     _num_balls
	jcs     L0003
	lda     (c_sp),y
	tay
	lda     _bact,y
	jeq     L0004
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L006F
	inx
	clc
L006F:	adc     #<(_bx)
	tay
	txa
	adc     #>(_bx)
	tax
	tya
	jsr     ldaxi
	ldy     #$0B
	jsr     incaxy
	txa
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	sta     sreg
	ldx     #$00
	ldy     #$04
	lda     (c_sp),y
	asl     a
	bcc     L0070
	inx
	clc
L0070:	adc     #<(_bx)
	tay
	txa
	adc     #>(_bx)
	tax
	tya
	jsr     ldaxi
	ldy     #$0B
	jsr     incaxy
	lsr     a
	lsr     a
	lsr     a
	ldx     #$00
	ora     sreg
	ldy     #$03
	sta     (c_sp),y
	iny
	lda     (c_sp),y
	tay
	lda     _by,y
	ldy     #$09
	jsr     incaxy
	jsr     asrax3
	ldy     #$02
	sta     (c_sp),y
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0071
	inx
	clc
L0071:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	jeq     L0090
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0072
	inx
	clc
L0072:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$03
	lda     (c_sp),y
	jsr     decax1
	clc
	adc     ptr1
	sta     ptr1
	txa
	adc     ptr1+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L000A
	ldy     #$03
	lda     (c_sp),y
	sec
	sbc     #$01
	jmp     L0096
L000A:	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0073
	inx
	clc
L0073:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	ldy     #$03
	lda     (c_sp),y
	jsr     incax1
	clc
	adc     ptr1
	sta     ptr1
	txa
	adc     ptr1+1
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L000C
	ldy     #$03
	jmp     L009A
L000C:	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	jsr     decax1
	jsr     aslax1
	clc
	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	bne     L000E
	ldy     #$02
	lda     (c_sp),y
	sec
	sbc     #$01
	jmp     L0096
L000E:	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	jsr     incax1
	jsr     aslax1
	clc
	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	jne     L0004
	ldy     #$02
L009A:	clc
	lda     #$01
	adc     (c_sp),y
L0096:	sta     (c_sp),y
	lda     #$00
L0090:	sta     _fsp
	ldy     #$02
	tax
	lda     (c_sp),y
	asl     a
	bcc     L0074
	inx
	clc
L0074:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0066
	inx
L0066:	sta     ptr1
	stx     ptr1+1
	lda     #$04
	ldy     #$00
	sta     (ptr1),y
	ldy     #$03
	lda     (c_sp),y
	sta     _fsx
	dey
	lda     (c_sp),y
	sta     _fsy
	lda     #$01
	sta     _fsp
FL_loop:
	lda     _fsp
	jeq     FL_done
	dec     _fsp
	ldx     _fsp
	lda     _fsx,x
	sta     $02
	lda     _fsy,x
	sta     $03
	asl     a
	tax
	lda     _pfr,x
	sta     $06
	lda     _pfr+1,x
	sta     $07
	dex
	dex
	lda     _pfr,x
	sta     $08
	lda     _pfr+1,x
	sta     $09
	inx
	inx
	inx
	inx
	lda     _pfr,x
	sta     $0a
	lda     _pfr+1,x
	sta     $0b
	ldy     $02
	iny
	lda     ($06),y
	bne     FL_sr
	lda     #4
	sta     ($06),y
	ldx     _fsp
	cpx     #200
	bcs     FL_sr
	tya
	sta     _fsx,x
	lda     $03
	sta     _fsy,x
	inc     _fsp
FL_sr:	ldy     $02
	dey
	lda     ($06),y
	bne     FL_sl
	lda     #4
	sta     ($06),y
	ldx     _fsp
	cpx     #200
	bcs     FL_sl
	tya
	sta     _fsx,x
	lda     $03
	sta     _fsy,x
	inc     _fsp
FL_sl:	ldy     $02
	lda     ($0a),y
	bne     FL_sd
	lda     #4
	sta     ($0a),y
	ldx     _fsp
	cpx     #200
	bcs     FL_sd
	tya
	sta     _fsx,x
	lda     $03
	clc
	adc     #1
	sta     _fsy,x
	inc     _fsp
FL_sd:	ldy     $02
	lda     ($08),y
	jne     FL_loop
	lda     #4
	sta     ($08),y
	ldx     _fsp
	cpx     #200
	jcs     FL_loop
	tya
	sta     _fsx,x
	lda     $03
	sec
	sbc     #1
	sta     _fsy,x
	inc     _fsp
	jmp     FL_loop
FL_done:
	nop
L0004:	ldy     #$04
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L006A
L0003:	lda     _filled_cells
	ldx     _filled_cells+1
	jsr     pushax
	lda     #$00
	sta     _filled_cells
	sta     _filled_cells+1
	lda     #$03
	ldy     #$02
L006D:	sta     (c_sp),y
	cmp     #$16
	jcs     L0013
	tya
	iny
L006C:	sta     (c_sp),y
	cmp     #$26
	jcs     L0014
	dey
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0075
	inx
	clc
L0075:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	bne     L001A
	ldy     #$02
	tax
	lda     (c_sp),y
	asl     a
	bcc     L0076
	inx
	clc
L0076:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0067
	inx
L0067:	sta     ptr1
	stx     ptr1+1
	lda     #$01
	jmp     L0097
L001A:	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0077
	inx
	clc
L0077:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	cmp     #$04
	bne     L001C
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0078
	inx
	clc
L0078:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0068
	inx
L0068:	sta     ptr1
	stx     ptr1+1
	lda     #$00
L0097:	ldy     #$00
	sta     (ptr1),y
L001C:	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0079
	inx
	clc
L0079:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	cmp     #$01
	bne     L0018
	inc     _filled_cells
	bne     L0018
	inc     _filled_cells+1
L0018:	ldy     #$03
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L006C
L0014:	dey
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L006D
L0013:	lda     _filled_cells
	sec
	ldy     #$00
	sbc     (c_sp),y
	sta     tmp1
	lda     _filled_cells+1
	iny
	sbc     (c_sp),y
	ora     tmp1
	bcc     L001F
	beq     L001F
	lda     _filled_cells
	sec
	dey
	sbc     (c_sp),y
	pha
	lda     _filled_cells+1
	iny
	sbc     (c_sp),y
	tax
	pla
	jsr     pushax
	lda     _level
	jsr     tosumula0
	clc
	adc     _score
	sta     _score
	txa
	adc     _score+1
	sta     _score+1
L001F:	jsr     incsp2
	lda     #$00
	ldy     #$04
L006E:	sta     (c_sp),y
	cmp     _num_balls
	jcs     L0095
	jsr     decsp5
	ldy     #$09
	lda     (c_sp),y
	tay
	lda     _bact,y
	jeq     L002A
	ldy     #$09
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L007A
	inx
	clc
L007A:	adc     #<(_bx)
	tay
	txa
	adc     #>(_bx)
	tax
	tya
	jsr     ldaxi
	jsr     incax6
	txa
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	sta     sreg
	ldx     #$00
	ldy     #$09
	lda     (c_sp),y
	asl     a
	bcc     L007B
	inx
	clc
L007B:	adc     #<(_bx)
	tay
	txa
	adc     #>(_bx)
	tax
	tya
	jsr     ldaxi
	clc
	adc     #$06
	lsr     a
	lsr     a
	lsr     a
	ldx     #$00
	ora     sreg
	ldy     #$04
	sta     (c_sp),y
	ldy     #$09
	lda     (c_sp),y
	asl     a
	bcc     L007C
	inx
	clc
L007C:	adc     #<(_bx)
	tay
	txa
	adc     #>(_bx)
	tax
	tya
	jsr     ldaxi
	ldy     #$11
	jsr     incaxy
	txa
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	sta     sreg
	ldx     #$00
	ldy     #$09
	lda     (c_sp),y
	asl     a
	bcc     L007D
	inx
	clc
L007D:	adc     #<(_bx)
	tay
	txa
	adc     #>(_bx)
	tax
	tya
	jsr     ldaxi
	ldy     #$11
	jsr     incaxy
	lsr     a
	lsr     a
	lsr     a
	ldx     #$00
	ora     sreg
	ldy     #$03
	sta     (c_sp),y
	ldy     #$09
	lda     (c_sp),y
	tay
	lda     _by,y
	jsr     incax4
	jsr     asrax3
	ldy     #$02
	sta     (c_sp),y
	ldy     #$09
	lda     (c_sp),y
	tay
	ldx     #$00
	lda     _by,y
	ldy     #$0F
	jsr     incaxy
	jsr     asrax3
	ldy     #$01
	sta     (c_sp),y
	iny
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L007E
	inx
	clc
L007E:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	cmp     #$01
	beq     L0092
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L007F
	inx
	clc
L007F:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	cmp     #$01
	beq     L0092
	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0080
	inx
	clc
L0080:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	cmp     #$01
	beq     L0092
	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0081
	inx
	clc
L0081:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	cmp     #$01
	beq     L0092
	lda     #$00
L0092:	ldy     #$00
	sta     (c_sp),y
	lda     (c_sp),y
	jeq     L002A
	lda     #$28
	jsr     pusha
	jmp     L0033
L002B:	ldy     #$0A
	lda     (c_sp),y
	asl     a
	bcc     L0082
	inx
	clc
L0082:	adc     #<(_bx)
	tay
	txa
	adc     #>(_bx)
	tax
	tya
	sta     ptr2
	stx     ptr2+1
	jsr     ldaxi
	sta     sreg
	stx     sreg+1
	lda     #<(_bdx)
	ldx     #>(_bdx)
	clc
	ldy     #$0A
	adc     (c_sp),y
	bcc     L002E
	inx
L002E:	ldy     #$00
	jsr     ldaidx
	clc
	adc     sreg
	pha
	txa
	adc     sreg+1
	tax
	pla
	sta     (ptr2),y
	iny
	txa
	sta     (ptr2),y
	lda     #<(_by)
	ldx     #>(_by)
	ldy     #$0A
	clc
	adc     (c_sp),y
	bcc     L002F
	inx
L002F:	sta     ptr2
	stx     ptr2+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     sreg
	lda     #<(_bdy)
	ldx     #>(_bdy)
	clc
	ldy     #$0A
	adc     (c_sp),y
	bcc     L0030
	inx
L0030:	ldy     #$00
	jsr     ldaidx
	clc
	adc     sreg
	sta     (ptr2),y
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0083
	inx
	clc
L0083:	adc     #<(_bx)
	tay
	txa
	adc     #>(_bx)
	tax
	tya
	jsr     ldaxi
	jsr     incax6
	txa
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	sta     sreg
	ldx     #$00
	ldy     #$0A
	lda     (c_sp),y
	asl     a
	bcc     L0084
	inx
	clc
L0084:	adc     #<(_bx)
	tay
	txa
	adc     #>(_bx)
	tax
	tya
	jsr     ldaxi
	clc
	adc     #$06
	lsr     a
	lsr     a
	lsr     a
	ldx     #$00
	ora     sreg
	ldy     #$05
	sta     (c_sp),y
	ldy     #$0A
	lda     (c_sp),y
	asl     a
	bcc     L0085
	inx
	clc
L0085:	adc     #<(_bx)
	tay
	txa
	adc     #>(_bx)
	tax
	tya
	jsr     ldaxi
	ldy     #$11
	jsr     incaxy
	txa
	asl     a
	asl     a
	asl     a
	asl     a
	asl     a
	sta     sreg
	ldx     #$00
	ldy     #$0A
	lda     (c_sp),y
	asl     a
	bcc     L0086
	inx
	clc
L0086:	adc     #<(_bx)
	tay
	txa
	adc     #>(_bx)
	tax
	tya
	jsr     ldaxi
	ldy     #$11
	jsr     incaxy
	lsr     a
	lsr     a
	lsr     a
	ldx     #$00
	ora     sreg
	ldy     #$04
	sta     (c_sp),y
	ldy     #$0A
	lda     (c_sp),y
	tay
	lda     _by,y
	jsr     incax4
	jsr     asrax3
	ldy     #$03
	sta     (c_sp),y
	ldy     #$0A
	lda     (c_sp),y
	tay
	ldx     #$00
	lda     _by,y
	ldy     #$0F
	jsr     incaxy
	jsr     asrax3
	ldy     #$02
	sta     (c_sp),y
	iny
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0087
	inx
	clc
L0087:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	cmp     #$01
	beq     L0033
	ldy     #$03
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0088
	inx
	clc
L0088:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	cmp     #$01
	beq     L0033
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L0089
	inx
	clc
L0089:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$05
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	cmp     #$01
	beq     L0033
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L008A
	inx
	clc
L008A:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	cmp     #$01
	bne     L002C
L0033:	ldy     #$00
	lda     (c_sp),y
	jsr     boolne
	php
	lda     (c_sp),y
	sec
	sbc     #$01
	sta     (c_sp),y
	plp
	jne     L002B
L002C:	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L008B
	inx
	clc
L008B:	adc     #<(_bx)
	tay
	txa
	adc     #>(_bx)
	tax
	tya
	jsr     ldaxi
	jsr     incax6
	cpx     #$00
	bne     L0038
	cmp     #$11
L0038:	bcs     L0037
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L008C
	inx
	clc
L008C:	adc     #<(_bx)
	sta     ptr1
	txa
	adc     #>(_bx)
	sta     ptr1+1
	lda     #$0B
	ldy     #$00
	sta     (ptr1),y
	iny
	lda     #$00
	sta     (ptr1),y
	ldy     #$0A
	lda     (c_sp),y
	tay
	lda     #$01
	sta     _bdx,y
L0037:	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L008D
	inx
	clc
L008D:	adc     #<(_bx)
	tay
	txa
	adc     #>(_bx)
	tax
	tya
	jsr     ldaxi
	ldy     #$11
	jsr     incaxy
	cmp     #$2F
	txa
	sbc     #$01
	bcc     L003A
	ldy     #$0A
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L008E
	inx
	clc
L008E:	adc     #<(_bx)
	sta     ptr1
	txa
	adc     #>(_bx)
	sta     ptr1+1
	lda     #$1D
	ldy     #$00
	sta     (ptr1),y
	iny
	tya
	sta     (ptr1),y
	ldy     #$0A
	lda     (c_sp),y
	tay
	lda     #$FF
	sta     _bdx,y
L003A:	ldy     #$0A
	lda     (c_sp),y
	tay
	ldx     #$00
	lda     _by,y
	jsr     incax4
	cmp     #$19
	txa
	sbc     #$00
	bvc     L003E
	eor     #$80
L003E:	bpl     L003C
	ldy     #$0A
	lda     (c_sp),y
	tay
	lda     #$15
	sta     _by,y
	ldy     #$0A
	lda     (c_sp),y
	tay
	lda     #$01
	sta     _bdy,y
L003C:	ldy     #$0A
	lda     (c_sp),y
	tay
	ldx     #$00
	lda     _by,y
	ldy     #$0F
	jsr     incaxy
	cmp     #$AF
	txa
	sbc     #$00
	bvs     L0043
	eor     #$80
L0043:	bpl     L0041
	ldy     #$0A
	lda     (c_sp),y
	tay
	lda     #$9F
	sta     _by,y
	ldy     #$0A
	lda     (c_sp),y
	tay
	lda     #$FF
	sta     _bdy,y
L0041:	jsr     incsp1
L002A:	jsr     incsp5
	ldy     #$04
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L006E
L0095:	lda     #$01
	sta     _fv_active
	lda     #$03
	sta     _fv_row
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; void __near__ fill_visual_row (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fill_visual_row: near

.segment	"CODE"

	lda     _fv_row
	asl     a
	tax
	lda     _pfr,x
	sta     $06
	lda     _pfr+1,x
	sta     $07
	lda     _scr_row,x
	sta     $08
	sta     $0a
	lda     _scr_row+1,x
	clc
	adc     #$4c
	sta     $09
	lda     _scr_row+1,x
	clc
	adc     #$d8
	sta     $0b
	ldy     #2
FV_loop:
	lda     ($06),y
	cmp     #1
	bne     FV_skip
	lda     ($08),y
	cmp     #128
	bne     FV_skip
	lda     #32
	sta     ($08),y
	lda     #0
	sta     ($0a),y
FV_skip:
	iny
	cpy     #38
	bne     FV_loop
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ fill_visual_step (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fill_visual_step: near

.segment	"CODE"

	jsr     decsp1
	lda     _fv_active
	beq     L0007
	lda     _fv_row
	clc
	adc     #$03
	ldy     #$00
	sta     (c_sp),y
	cmp     #$17
	bcc     L0008
	lda     #$16
	sta     (c_sp),y
	jmp     L0008
L0004:	jsr     _fill_visual_row
	inc     _fv_row
L0008:	lda     _fv_row
	ldy     #$00
	cmp     (c_sp),y
	bcc     L0004
	lda     _fv_row
	cmp     #$16
	bcc     L0007
	sty     _fv_active
L0007:	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ advance_walls (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_advance_walls: near

.segment	"CODE"

	jsr     decsp3
	inc     _wall_tick
	lda     _wall_tick
	and     #$01
	jne     L0004
	ldy     #$02
L001B:	sta     (c_sp),y
	cmp     #$02
	jcs     L0004
	lda     (c_sp),y
	tay
	lda     _wact,y
	jeq     L0005
	ldy     #$02
	lda     (c_sp),y
	tay
	lda     _wcx,y
	sta     sreg
	lda     #<(_wdcx)
	ldx     #>(_wdcx)
	clc
	ldy     #$02
	adc     (c_sp),y
	bcc     L000A
	inx
L000A:	ldy     #$00
	jsr     ldaidx
	clc
	adc     sreg
	iny
	sta     (c_sp),y
	iny
	lda     (c_sp),y
	tay
	lda     _wcy,y
	sta     sreg
	lda     #<(_wdcy)
	ldx     #>(_wdcy)
	clc
	ldy     #$02
	adc     (c_sp),y
	bcc     L000C
	inx
L000C:	ldy     #$00
	jsr     ldaidx
	clc
	adc     sreg
	sta     (c_sp),y
	iny
	lda     (c_sp),y
	cmp     #$02
	bcc     L001E
	cmp     #$26
	bcs     L001E
	dey
	lda     (c_sp),y
	cmp     #$03
	bcc     L001E
	cmp     #$16
	bcs     L001E
	ldx     #$00
	lda     (c_sp),y
	asl     a
	bcc     L001C
	inx
	clc
L001C:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	beq     L000D
L001E:	ldy     #$02
	lda     (c_sp),y
	jsr     _solidify_wall
	ldy     #$02
	lda     (c_sp),y
	tay
	lda     #$00
	sta     _wact,y
	lda     _wact
	ora     _wact+1
	sta     _walls_building
	lda     _walls_building
	bne     L0005
	jsr     _fill_regions
	jmp     L0005
L000D:	ldy     #$01
	lda     (c_sp),y
	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	jsr     pusha
	lda     #$80
	jsr     pusha
	ldy     #$05
	lda     (c_sp),y
	tay
	lda     _wcol,y
	jsr     _scr_put
	ldx     #$00
	lda     (c_sp,x)
	asl     a
	bcc     L001D
	inx
	clc
L001D:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L001A
	inx
L001A:	sta     ptr1
	stx     ptr1+1
	iny
	lda     (c_sp),y
	tay
	lda     _wpfv,y
	ldy     #$00
	sta     (ptr1),y
	ldy     #$02
	lda     (c_sp),y
	tax
	dey
	lda     (c_sp),y
	sta     _wcx,x
	iny
	lda     (c_sp),y
	tax
	ldy     #$00
	lda     (c_sp),y
	sta     _wcy,x
L0005:	ldy     #$02
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L001B
L0004:	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ start_wall (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_start_wall: near

.segment	"CODE"

	lda     _cursor_px
	ldx     _cursor_px+1
	ldy     #$0C
	jsr     incaxy
	jsr     shrax3
	jsr     pusha
	ldx     #$00
	lda     _cursor_py
	ldy     #$0A
	jsr     incaxy
	jsr     asrax3
	jsr     pusha
	ldx     #$00
	lda     (c_sp,x)
	asl     a
	bcc     L0015
	inx
	clc
L0015:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	jne     L0001
	lda     _wact
	jne     L0001
	lda     _wact+1
	jne     L0001
	lda     #$01
	sta     _wact
	tay
	lda     (c_sp),y
	sta     _wcx
	dey
	lda     (c_sp),y
	sta     _wcy
	lda     _wall_dir
	beq     L0019
	tya
	jmp     L001A
L0019:	lda     #$01
L001A:	cmp     #$80
	sta     _wdcx
	lda     _wall_dir
	beq     L001B
	lda     #$01
L001B:	cmp     #$80
	sta     _wdcy
	lda     #$02
	sta     _wcol
	sta     _wpfv
	lda     #$01
	sta     _wact+1
	iny
	lda     (c_sp),y
	sta     _wcx+1
	dey
	lda     (c_sp),y
	sta     _wcy+1
	lda     _wall_dir
	beq     L000C
	tya
	jmp     L001C
L000C:	lda     #$FF
L001C:	cmp     #$80
	sta     _wdcx+1
	lda     _wall_dir
	beq     L0010
	lda     #$FF
L0010:	cmp     #$80
	sta     _wdcy+1
	lda     #$06
	sta     _wcol+1
	lda     #$03
	sta     _wpfv+1
	iny
	lda     (c_sp),y
	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	jsr     pusha
	lda     #$80
	jsr     pusha
	lda     #$02
	jsr     _scr_put
	ldx     #$00
	lda     (c_sp,x)
	asl     a
	bcc     L0016
	inx
	clc
L0016:	adc     #<(_pfr)
	tay
	txa
	adc     #>(_pfr)
	tax
	tya
	jsr     ldaxi
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (c_sp),y
	clc
	adc     ptr1
	ldx     ptr1+1
	bcc     L0014
	inx
L0014:	sta     ptr1
	stx     ptr1+1
	lda     #$02
	dey
	sta     (ptr1),y
	lda     #$01
	sta     _walls_building
L0001:	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ read_input (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_read_input: near

.segment	"CODE"

	lda     $DC00
	eor     #$FF
	and     #$1F
	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	and     #$10
	beq     L0021
	lda     _joy_prev
	and     #$10
	beq     L0020
	tya
	jmp     L0021
L0020:	lda     #$01
L0021:	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	and     #$0F
	jsr     pusha
	ldy     #$00
	lda     (c_sp),y
	jeq     L0032
	and     #$0C
	beq     L0023
	sty     _wall_dir
L0023:	lda     (c_sp),y
	and     #$03
	beq     L0025
	lda     #$01
	sta     _wall_dir
L0025:	lda     _joy_prev
	and     #$0F
	cmp     (c_sp),y
	bne     L0026
	lda     _joy_hold_frames
	cmp     #$FF
	bcs     L0027
	inc     _joy_hold_frames
	jmp     L0027
L0026:	sty     _joy_hold_frames
L0027:	lda     _joy_hold_frames
	cmp     #$03
	jcc     L001A
	lda     _cursor_px
	ldx     _cursor_px+1
	jsr     pushax
	lda     _cursor_py
	jsr     pusha
	ldy     #$03
	lda     (c_sp),y
	and     #$01
	beq     L002A
	ldy     #$00
	lda     (c_sp),y
	cmp     #$1E
	bcc     L0028
	sec
	sbc     #$06
	jmp     L001C
L0028:	lda     #$18
L001C:	sta     (c_sp),y
	ldy     #$03
L002A:	lda     (c_sp),y
	and     #$02
	beq     L002D
	ldx     #$00
	lda     (c_sp,x)
	jsr     incax6
	cmp     #$B0
	txa
	sbc     #$00
	bvc     L0011
	eor     #$80
L0011:	bpl     L002B
	ldy     #$00
	clc
	lda     #$06
	adc     (c_sp),y
	jmp     L001D
L002B:	lda     #$AF
	ldy     #$00
L001D:	sta     (c_sp),y
	ldy     #$03
L002D:	lda     (c_sp),y
	and     #$04
	beq     L0030
	dey
	jsr     ldaxysp
	cmp     #$16
	txa
	sbc     #$00
	ldx     #$00
	bcc     L002E
	lda     #$06
	ldy     #$01
	jsr     subeqysp
	jmp     L0015
L002E:	lda     #$10
	ldy     #$01
	jsr     staxysp
L0015:	ldy     #$03
L0030:	lda     (c_sp),y
	and     #$08
	beq     L0019
	dey
	jsr     ldaxysp
	jsr     incax6
	cpx     #$01
	bne     L0018
	cmp     #$30
L0018:	bcs     L0017
	ldy     #$01
	ldx     #$00
	lda     #$06
	jsr     addeqysp
	jmp     L0019
L0017:	ldx     #$01
	lda     #$2F
	ldy     #$01
	jsr     staxysp
L0019:	ldy     #$02
	jsr     ldaxysp
	sta     _cursor_px
	stx     _cursor_px+1
	ldy     #$00
	lda     (c_sp),y
	sta     _cursor_py
	jsr     incsp3
	jmp     L001A
L0032:	sta     _joy_hold_frames
L001A:	ldy     #$01
	lda     (c_sp),y
	beq     L001B
	jsr     _start_wall
L001B:	ldy     #$02
	lda     (c_sp),y
	sta     _joy_prev
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ update_cursor (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_update_cursor: near

.segment	"CODE"

	lda     _wall_dir
	cmp     _last_cursor_dir
	beq     L0007
	lda     _wall_dir
	beq     L0005
	lda     #$21
	jmp     L0006
L0005:	lda     #$20
L0006:	sta     $4FF8
	lda     _wall_dir
	sta     _last_cursor_dir
L0007:	lda     #$00
	jsr     pusha
	lda     _cursor_px
	ldx     _cursor_px+1
	ldy     #$18
	jsr     incaxy
	jsr     pushax
	ldx     #$00
	lda     _cursor_py
	ldy     #$32
	jsr     incaxy
	jmp     _set_spr

.endproc

; ---------------------------------------------------------------
; void __near__ init_level (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_level: near

.segment	"CODE"

	jsr     decsp2
	jsr     _clear_screen
	lda     #$00
	sta     $D021
	sta     $D020
	jsr     _draw_border
	jsr     _clear_field
	ldx     #$02
	lda     #$AC
	sta     _total_cells
	stx     _total_cells+1
	lda     #$00
	sta     _filled_cells
	sta     _filled_cells+1
	lda     _total_cells
	ldx     _total_cells+1
	jsr     shrax2
	jsr     mulax3
	sta     _fill_target
	stx     _fill_target+1
	lda     #$00
	sta     _fv_active
	tax
	lda     #$A0
	sta     _cursor_px
	stx     _cursor_px+1
	lda     #$64
	sta     _cursor_py
	stx     _wall_dir
	lda     #$FF
	sta     _last_cursor_dir
	txa
	sta     _wact
	sta     _wact+1
	sta     _walls_building
	lda     _level
	clc
	adc     #$01
	ldy     #$00
	sta     (c_sp),y
	cmp     #$08
	bcc     L0015
	lda     #$07
	sta     (c_sp),y
L0015:	lda     (c_sp),y
	sta     _lives
	lda     (c_sp),y
	jsr     pusha0
	lda     #$1E
	jsr     tosumula0
	sta     _time_left
	stx     _time_left+1
	lda     #$00
	sta     _time_frames
	jsr     _draw_hud_labels
	jsr     _draw_hud
	lda     #$00
	sta     $D015
	jsr     decsp4
	lda     _level
	cmp     #$64
	bcc     L0016
	lda     #$03
	jmp     L0018
L0016:	lda     _level
	cmp     #$0A
	bcc     L0017
	lda     #$02
	jmp     L0018
L0017:	lda     #$01
L0018:	ldy     #$03
	sta     (c_sp),y
	clc
	adc     #$08
	dey
	sta     (c_sp),y
	lda     #$14
	jsr     pusha0
	ldy     #$04
	lda     (c_sp),y
	lsr     a
	jsr     tossuba0
	ldy     #$01
	sta     (c_sp),y
	jsr     pusha
	lda     #$0C
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     #$00
	jsr     _scr_put
	ldy     #$01
	lda     (c_sp),y
	clc
	adc     #$01
	jsr     pusha
	lda     #$0C
	jsr     pusha
	lda     #<(S01BC)
	ldx     #>(S01BC)
	jsr     pushax
	lda     #$01
	jsr     _scrwrite
	ldy     #$01
	lda     (c_sp),y
	clc
	adc     #$07
	jsr     pusha
	lda     #$0C
	jsr     pusha
	lda     _level
	jsr     pusha0
	lda     #$01
	jsr     _scr_num
	ldy     #$01
	lda     (c_sp),y
	clc
	adc     #$07
	sta     ptr1
	ldy     #$03
	lda     (c_sp),y
	clc
	adc     ptr1
	jsr     pusha
	lda     #$0C
	jsr     pusha
	lda     #$20
	jsr     pusha
	lda     #$00
	jsr     _scr_put
	lda     #$00
	ldy     #$05
L0012:	sta     (c_sp),y
	cmp     #$3C
	bcs     L0008
	jsr     _waitvsync
	ldy     #$05
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0012
L0008:	ldy     #$01
	lda     (c_sp),y
	dey
L0013:	sta     (c_sp),y
	lda     (c_sp),y
	jsr     pusha0
	ldy     #$04
	lda     (c_sp),y
	clc
	dey
	adc     (c_sp),y
	bcc     L0010
	inx
L0010:	jsr     tosicmp
	bpl     L000C
	ldy     #$00
	lda     (c_sp),y
	jsr     pusha
	lda     #$0C
	jsr     pusha
	lda     #$80
	jsr     pusha
	lda     #$0F
	jsr     _scr_put
	ldy     #$00
	lda     (c_sp),y
	clc
	adc     _pfr+24
	ldx     _pfr+24+1
	bcc     L0011
	inx
L0011:	sta     ptr1
	stx     ptr1+1
	tya
	sta     (ptr1),y
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0013
L000C:	jsr     incsp4
	ldy     #$00
	lda     (c_sp),y
	jsr     _init_balls
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ title_screen (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_title_screen: near

.segment	"CODE"

	jsr     _clear_screen
	lda     #$00
	sta     $D021
	sta     $D020
	sta     $D015
	lda     #$0C
	jsr     pusha
	lda     #$03
	jsr     pusha
	lda     #<(S01BD)
	ldx     #>(S01BD)
	jsr     pushax
	lda     #$01
	jsr     _scrwrite
	lda     #$08
	jsr     pusha
	lda     #$07
	jsr     pusha
	lda     #<(S01BE)
	ldx     #>(S01BE)
	jsr     pushax
	lda     #$0F
	jsr     _scrwrite
	lda     #$06
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #<(S01BF)
	ldx     #>(S01BF)
	jsr     pushax
	lda     #$01
	jsr     _scrwrite
	lda     #$06
	jsr     pusha
	lda     #$0C
	jsr     pusha
	lda     #<(S01C0)
	ldx     #>(S01C0)
	jsr     pushax
	lda     #$02
	jsr     _scrwrite
	lda     #$10
	jsr     pusha
	lda     #$0C
	jsr     pusha
	lda     #<(S01C1)
	ldx     #>(S01C1)
	jsr     pushax
	lda     #$0C
	jsr     _scrwrite
	lda     #$06
	jsr     pusha
	lda     #$0D
	jsr     pusha
	lda     #<(S01C2)
	ldx     #>(S01C2)
	jsr     pushax
	lda     #$06
	jsr     _scrwrite
	lda     #$0D
	jsr     pusha
	jsr     pusha
	lda     #<(S01C3)
	ldx     #>(S01C3)
	jsr     pushax
	lda     #$0C
	jsr     _scrwrite
	lda     #$06
	jsr     pusha
	lda     #$0E
	jsr     pusha
	lda     #<(S01C4)
	ldx     #>(S01C4)
	jsr     pushax
	lda     #$01
	jsr     _scrwrite
	lda     #$0A
	jsr     pusha
	lda     #$0E
	jsr     pusha
	lda     #<(S01C5)
	ldx     #>(S01C5)
	jsr     pushax
	lda     #$0C
	jsr     _scrwrite
	lda     #$08
	jsr     pusha
	lda     #$11
	jsr     pusha
	lda     #<(S01C6)
	ldx     #>(S01C6)
	jsr     pushax
	lda     #$07
	jsr     _scrwrite
	lda     #$0B
	jsr     pusha
	lda     #$15
	jsr     pusha
	lda     #<(S01C7)
	ldx     #>(S01C7)
	jsr     pushax
	lda     #$0D
	jsr     _scrwrite
L0005:	jsr     decsp1
	jsr     _waitvsync
	lda     $DC00
	eor     #$FF
	and     #$1F
	ldy     #$00
	sta     (c_sp),y
	and     #$10
	beq     L0006
	jsr     incsp1
	jmp     L000B
L0006:	jsr     _kbhit
	tax
	beq     L0007
	jsr     _cgetc
	jsr     incsp1
	jmp     L000B
L0007:	jsr     incsp1
	jmp     L0005
L0008:	jsr     _waitvsync
L000B:	lda     $DC00
	eor     #$FF
	and     #$10
	bne     L0008
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ game_over_screen (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_game_over_screen: near

.segment	"CODE"

	jsr     decsp1
	lda     #$00
	sta     $D015
	tay
L0012:	sta     (c_sp),y
	cmp     #$0A
	bcs     L0003
	lda     #$02
	sta     $D020
	jsr     _waitvsync
	jsr     _waitvsync
	jsr     _waitvsync
	lda     #$00
	sta     $D020
	jsr     _waitvsync
	jsr     _waitvsync
	jsr     _waitvsync
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0012
L0003:	lda     _time_left
	ora     _time_left+1
	bne     L0014
	lda     #$0E
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #<(S01C8)
	ldx     #>(S01C8)
	jmp     L0017
L0014:	lda     #$0E
	jsr     pusha
	lda     #$0A
	jsr     pusha
	lda     #<(S01C9)
	ldx     #>(S01C9)
L0017:	jsr     pushax
	lda     #$02
	jsr     _scrwrite
	lda     #$0C
	jsr     pusha
	jsr     pusha
	lda     #<(S01CA)
	ldx     #>(S01CA)
	jsr     pushax
	lda     #$01
	jsr     _scrwrite
	lda     #$13
	jsr     pusha
	lda     #$0C
	jsr     pusha
	lda     _score
	ldx     _score+1
	jsr     pushax
	lda     #$01
	jsr     _scr_num
	lda     #$0B
	jsr     pusha
	lda     #$0E
	jsr     pusha
	lda     #<(S01CB)
	ldx     #>(S01CB)
	jsr     pushax
	lda     #$0C
	jsr     _scrwrite
	lda     #$1A
	jsr     pusha
	lda     #$0E
	jsr     pusha
	lda     _level
	jsr     pusha0
	lda     #$0C
	jsr     _scr_num
	lda     #$0A
	jsr     pusha
	lda     #$11
	jsr     pusha
	lda     #<(S01CC)
	ldx     #>(S01CC)
	jsr     pushax
	lda     #$0D
	jsr     _scrwrite
L000C:	jsr     decsp1
	jsr     _waitvsync
	lda     $DC00
	eor     #$FF
	and     #$1F
	ldy     #$00
	sta     (c_sp),y
	and     #$10
	beq     L000D
	jsr     incsp1
	jmp     L0015
L000D:	jsr     _kbhit
	tax
	beq     L000E
	jsr     _cgetc
	jsr     incsp1
	jmp     L0015
L000E:	jsr     incsp1
	jmp     L000C
L000F:	jsr     _waitvsync
L0015:	lda     $DC00
	eor     #$FF
	and     #$10
	bne     L000F
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     _setup_vic
	jsr     _init_sprites
L0002:	jsr     _title_screen
	lda     #$01
	sta     _level
	lda     #$00
	sta     _score
	sta     _score+1
	lda     #$02
	sta     _lives
	lda     #$00
	sta     _game_over
	sta     _joy_prev
	sta     _frame_count
	jsr     _init_level
	jmp     L0025
L0003:	jsr     _waitvsync
	inc     _frame_count
	inc     _time_frames
	lda     _time_frames
	cmp     _frames_per_sec
	bcc     L000A
	lda     #$00
	sta     _time_frames
	lda     _time_left
	ora     _time_left+1
	beq     L0007
	ldx     _time_left
	bne     L0009
	dec     _time_left+1
L0009:	dex
	stx     _time_left
L0007:	lda     _time_left
	ora     _time_left+1
	bne     L000A
	lda     #$01
	sta     _game_over
L000A:	jsr     _read_input
	jsr     _advance_walls
	jsr     _fill_visual_step
	jsr     _update_balls
	jsr     _update_cursor
L002B:	lda     $D012
	cmp     #$FA
	bcc     L002B
	jsr     _flush_sprites
	lda     _frame_count
	and     #$3F
	bne     L000F
	jsr     _draw_hud
L000F:	lda     _fv_active
	jne     L002E
	lda     _filled_cells
	cmp     _fill_target
	lda     _filled_cells+1
	sbc     _fill_target+1
	jcc     L002E
	jsr     _draw_hud
	jsr     decsp1
	lda     #$00
	tay
L0027:	sta     (c_sp),y
	cmp     #$1E
	bcs     L0016
	jsr     _waitvsync
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0027
L0016:	jsr     incsp1
	lda     _level
	jsr     pusha0
	lda     #$64
	jsr     tosumula0
	clc
	adc     _time_left
	pha
	txa
	adc     _time_left+1
	tax
	pla
	clc
	adc     _score
	sta     _score
	txa
	adc     _score+1
	sta     _score+1
	jsr     _draw_hud
	jsr     decsp1
	lda     #$00
	tay
L0028:	sta     (c_sp),y
	cmp     #$14
	bcs     L001A
	jsr     _waitvsync
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0028
L001A:	jsr     incsp1
	tya
	sta     $D015
	jsr     decsp1
	tay
L0029:	sta     (c_sp),y
	cmp     #$0F
	bcs     L002D
	jsr     _waitvsync
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L0029
L002D:	tya
L002A:	sta     (c_sp),y
	cmp     #$0F
	bcs     L0022
	lda     #$05
	sta     $D020
	jsr     _waitvsync
	jsr     _waitvsync
	lda     #$00
	sta     $D020
	jsr     _waitvsync
	jsr     _waitvsync
	ldy     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	jmp     L002A
L0022:	jsr     incsp1
	inc     _level
	jsr     _init_level
L002E:	lda     _lives
	bne     L0025
	lda     #$01
	sta     _game_over
L0025:	lda     _game_over
	jeq     L0003
	cmp     #$01
	bne     L0026
	jsr     _game_over_screen
	jmp     L0002
L0026:	jsr     _restore_vic
	lda     #$00
	sta     $D015
	tax
	rts

.endproc

